### ISSUE TITLE
Building the docker image fails

### ISSUE THREAD

**Issue by bogdanb** [atlassian-labs/connect-security-req-tester#68]
**Describe the bug**
I tried to build the docker image as described in the README and I get an error:

```
$ docker build -t connect-security-req-tester .
Sending build context to Docker daemon  736.3kB
Step 1/9 : FROM python:3.9-slim
 ---> 4af03d07a3c9
Step 2/9 : RUN pip install pipenv
 ---> Using cache
 ---> b5babb911705
Step 3/9 : RUN apt update && apt install build-essential -y
 ---> Using cache
 ---> d71077849165
Step 4/9 : RUN useradd -m app
 ---> Using cache
 ---> 06856c0b3c09
Step 5/9 : USER app
 ---> Using cache
 ---> cdfd4c6b6d08
Step 6/9 : WORKDIR /app
 ---> Using cache
 ---> a6cb74d42ab0
Step 7/9 : COPY . /app
 ---> Using cache
 ---> 923418f9f7e2
Step 8/9 : RUN pipenv install --system
 ---> Running in 26ef623827ca
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 233, in install
    do_install(
  File "/usr/local/lib/python3.9/site-packages/pipenv/routines/install.py", line 61, in do_install
    ensure_project(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/project.py", line 26, in ensure_project
    if project.s.PIPENV_USE_SYSTEM or project.virtualenv_exists:
  File "/usr/local/lib/python3.9/site-packages/pipenv/project.py", line 252, in virtualenv_exists
    if os.path.exists(self.virtualenv_location):
  File "/usr/local/lib/python3.9/site-packages/pipenv/project.py", line 449, in virtualenv_location
    self._virtualenv_location = self.get_location_for_virtualenv()
  File "/usr/local/lib/python3.9/site-packages/pipenv/project.py", line 274, in get_location_for_virtualenv
    return str(get_workon_home().joinpath(self.virtualenv_name))
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/shell.py", line 195, in get_workon_home
    os.makedirs(expanded_path, exist_ok=True)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/app/.local'
The command '/bin/sh -c pipenv install --system' returned a non-zero code: 1
```

Not sure what info would be relevant, but just in case:
```
$ uname -a
Linux dev.qotilabs.com 5.4.0 #1 SMP Mon Mar 16 15:39:59 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux
$ docker --version
Docker version 20.10.25, build 20.10.25-0ubuntu1~20.04.1
$ git log -1
commit 8bd13456dd102a045c31f55957885e527c5122d4 (HEAD -> main, origin/main, origin/HEAD)
Merge: 70574c0 5faba6a
Author: sgandrathi <117855901+sgandrathi@users.noreply.github.com>
Date:   Thu Aug 10 08:14:45 2023 -0700

    Merge pull request #66 from atlassian-labs/authnchecks

    Authnchecks
```

**Comment by sgandrathi** [comment]
Hi @bogdanb, thank you for raising this bug. I tried building the docker image on x86_64 arch Linux image and was unable to reproduce the above permissions failure with same commands. Please check your user permissions to debug this issue.

Regarding publishing images to DockerHub, we don't have any plans as of now. However, we will look into it and announce it in case we publish an image.
